# String filename
filename: BlackWalk.mid

# integer seed for random values
seed: 0

# note pitch is denoted by its midi-value, integer.
# a midi-value ranges from 0-127. middle C (scientific C4) is 60.
# compare https://en.wikipedia.org/wiki/Scientific_pitch_notation#Table_of_note_frequencies
# here the firstPitch must be a black key.
# it must  hold: min <= first <= max
minPitch: 48 # C3
maxPitch: 95 # B6
firstPitch: 73 # C#5

# note duration is denoted by the divisor, integer.
# 1 -> full note, 2 -> half note, 4 -> quarter note, and so on.
# here the note duration divisor must be from [1, 2, 4, 8, 16, 32, 64] (power of 2).
# it must hold: 1/min <= 1/first <= 1/max
minDuration: 16
maxDuration: 2
firstDuration: 4